<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MatchProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('match_profiles')->delete();
        
        \DB::table('match_profiles')->insert(array (
            0 => 
            array (
                'id' => 44,
                'user_id' => 33,
                'looking_for' => 'Bride',
                'from_age' => 40,
                'to_age' => 45,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Widowed',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-02-14 09:12:26',
                'updated_at' => '2025-02-14 09:12:26',
            ),
            1 => 
            array (
                'id' => 55,
                'user_id' => 66,
                'looking_for' => 'Groom',
                'from_age' => 32,
                'to_age' => 34,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '6\'0"',
                'created_at' => '2025-02-24 16:48:54',
                'updated_at' => '2025-02-24 16:48:54',
            ),
            2 => 
            array (
                'id' => 56,
                'user_id' => 129,
                'looking_for' => 'Groom',
                'from_age' => 25,
                'to_age' => 35,
                'religion' => 'Islam',
                'education' => 'Doctorate',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '5\'11"',
                'created_at' => '2025-03-04 13:18:19',
                'updated_at' => '2025-03-04 13:31:59',
            ),
            3 => 
            array (
                'id' => 58,
                'user_id' => 185,
                'looking_for' => 'Groom',
                'from_age' => 21,
                'to_age' => 23,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '5\'9"',
                'created_at' => '2025-03-18 01:38:58',
                'updated_at' => '2025-03-18 01:38:58',
            ),
            4 => 
            array (
                'id' => 59,
                'user_id' => 180,
                'looking_for' => 'Groom',
                'from_age' => 21,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '5\'10"',
                'created_at' => '2025-03-18 02:15:00',
                'updated_at' => '2025-03-18 02:15:00',
            ),
            5 => 
            array (
                'id' => 60,
                'user_id' => 186,
                'looking_for' => 'Bride',
                'from_age' => 39,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'10"',
                'height_to' => '5\'6"',
                'created_at' => '2025-03-18 05:58:14',
                'updated_at' => '2025-03-18 05:58:14',
            ),
            6 => 
            array (
                'id' => 61,
                'user_id' => 187,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'6"',
                'created_at' => '2025-03-18 06:09:17',
                'updated_at' => '2025-03-18 06:09:17',
            ),
            7 => 
            array (
                'id' => 62,
                'user_id' => 179,
                'looking_for' => 'Groom',
                'from_age' => 29,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Diploma in Engineering',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'9"',
                'height_to' => '5\'10"',
                'created_at' => '2025-03-18 22:28:16',
                'updated_at' => '2025-03-18 22:28:16',
            ),
            8 => 
            array (
                'id' => 64,
                'user_id' => 195,
                'looking_for' => 'Groom',
                'from_age' => 24,
                'to_age' => 28,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'8"',
                'created_at' => '2025-03-19 10:56:39',
                'updated_at' => '2025-03-19 10:56:39',
            ),
            9 => 
            array (
                'id' => 65,
                'user_id' => 163,
                'looking_for' => 'Bride',
                'from_age' => NULL,
                'to_age' => 23,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5.0\'',
                'height_to' => '5.3\'',
                'created_at' => '2025-03-19 15:56:29',
                'updated_at' => '2025-03-19 15:56:29',
            ),
            10 => 
            array (
                'id' => 66,
                'user_id' => 178,
                'looking_for' => 'Bride',
                'from_age' => NULL,
                'to_age' => 23,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5.0\'',
                'height_to' => '5.3\'',
                'created_at' => '2025-03-20 10:03:05',
                'updated_at' => '2025-03-20 10:03:05',
            ),
            11 => 
            array (
                'id' => 68,
                'user_id' => 192,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-03-20 16:08:35',
                'updated_at' => '2025-03-20 23:16:05',
            ),
            12 => 
            array (
                'id' => 69,
                'user_id' => 198,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 31,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '5\'9"',
                'created_at' => '2025-03-20 20:14:49',
                'updated_at' => '2025-03-20 20:14:49',
            ),
            13 => 
            array (
                'id' => 70,
                'user_id' => 200,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'5"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-21 06:06:23',
                'updated_at' => '2025-03-21 06:06:23',
            ),
            14 => 
            array (
                'id' => 71,
                'user_id' => 201,
                'looking_for' => 'Groom',
                'from_age' => 31,
                'to_age' => 31,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'4"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-21 10:24:07',
                'updated_at' => '2025-03-21 10:24:07',
            ),
            15 => 
            array (
                'id' => 72,
                'user_id' => 202,
                'looking_for' => 'Bride',
                'from_age' => 19,
                'to_age' => 19,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Sylhet',
                'height_from' => '5\'3"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-21 10:26:40',
                'updated_at' => '2025-03-21 10:26:40',
            ),
            16 => 
            array (
                'id' => 73,
                'user_id' => 203,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 20,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Rajshahi',
                'height_from' => '5\'2"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-21 11:33:28',
                'updated_at' => '2025-03-21 11:33:28',
            ),
            17 => 
            array (
                'id' => 74,
                'user_id' => 204,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'8"',
                'created_at' => '2025-03-21 12:29:19',
                'updated_at' => '2025-03-21 12:29:19',
            ),
            18 => 
            array (
                'id' => 75,
                'user_id' => 205,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 24,
                'religion' => 'Hindu',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-21 13:04:49',
                'updated_at' => '2025-03-21 13:04:49',
            ),
            19 => 
            array (
                'id' => 76,
                'user_id' => 206,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 20,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-21 14:30:58',
                'updated_at' => '2025-03-21 14:30:58',
            ),
            20 => 
            array (
                'id' => 77,
                'user_id' => 207,
                'looking_for' => 'Groom',
                'from_age' => 28,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'3"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-21 14:46:12',
                'updated_at' => '2025-03-21 14:46:12',
            ),
            21 => 
            array (
                'id' => 78,
                'user_id' => 149,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'0"',
                'height_to' => '6\'0"',
                'created_at' => '2025-03-21 15:23:24',
                'updated_at' => '2025-03-21 15:23:24',
            ),
            22 => 
            array (
                'id' => 79,
                'user_id' => 209,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-21 20:01:06',
                'updated_at' => '2025-03-21 20:01:06',
            ),
            23 => 
            array (
                'id' => 80,
                'user_id' => 212,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 32,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Mymensingh',
                'height_from' => '5\'6"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-22 03:53:12',
                'updated_at' => '2025-03-22 05:18:15',
            ),
            24 => 
            array (
                'id' => 81,
                'user_id' => 213,
                'looking_for' => 'Groom',
                'from_age' => 21,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Sylhet',
                'height_from' => '5\'1"',
                'height_to' => '5\'6"',
                'created_at' => '2025-03-22 05:54:55',
                'updated_at' => '2025-03-22 05:56:42',
            ),
            25 => 
            array (
                'id' => 82,
                'user_id' => 214,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => 'Doctorate',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-22 08:55:53',
                'updated_at' => '2025-03-22 08:55:53',
            ),
            26 => 
            array (
                'id' => 83,
                'user_id' => 215,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'4"',
                'height_to' => NULL,
                'created_at' => '2025-03-22 10:17:11',
                'updated_at' => '2025-03-22 10:17:11',
            ),
            27 => 
            array (
                'id' => 84,
                'user_id' => 216,
                'looking_for' => 'Groom',
                'from_age' => 25,
                'to_age' => 21,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'4"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-22 11:26:01',
                'updated_at' => '2025-03-22 11:26:01',
            ),
            28 => 
            array (
                'id' => 85,
                'user_id' => 219,
                'looking_for' => 'Bride',
                'from_age' => 28,
                'to_age' => 31,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'6"',
                'created_at' => '2025-03-22 12:54:17',
                'updated_at' => '2025-03-22 12:54:17',
            ),
            29 => 
            array (
                'id' => 86,
                'user_id' => 220,
                'looking_for' => 'Groom',
                'from_age' => 27,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-22 13:59:15',
                'updated_at' => '2025-03-22 13:59:15',
            ),
            30 => 
            array (
                'id' => 87,
                'user_id' => 221,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 26,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'0"',
                'height_to' => '5\'8"',
                'created_at' => '2025-03-22 14:39:55',
                'updated_at' => '2025-03-22 14:39:55',
            ),
            31 => 
            array (
                'id' => 88,
                'user_id' => 222,
                'looking_for' => 'Groom',
                'from_age' => 28,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => NULL,
                'height_to' => '5\'7"',
                'created_at' => '2025-03-22 14:41:20',
                'updated_at' => '2025-03-22 14:41:20',
            ),
            32 => 
            array (
                'id' => 89,
                'user_id' => 223,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 19,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Barishal',
                'height_from' => '6\'1"',
                'height_to' => '5\'3"',
                'created_at' => '2025-03-22 15:34:50',
                'updated_at' => '2025-03-22 15:34:50',
            ),
            33 => 
            array (
                'id' => 90,
                'user_id' => 225,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 26,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'1"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-22 19:17:12',
                'updated_at' => '2025-03-22 19:36:29',
            ),
            34 => 
            array (
                'id' => 91,
                'user_id' => 224,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 20,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Khulna',
                'height_from' => '5\'1"',
                'height_to' => '5\'1"',
                'created_at' => '2025-03-22 19:17:34',
                'updated_at' => '2025-03-22 19:17:34',
            ),
            35 => 
            array (
                'id' => 92,
                'user_id' => 226,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 19,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-22 19:57:44',
                'updated_at' => '2025-03-22 19:57:44',
            ),
            36 => 
            array (
                'id' => 93,
                'user_id' => 227,
                'looking_for' => 'Bride',
                'from_age' => 22,
                'to_age' => 26,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'4"',
                'height_to' => '5\'2"',
                'created_at' => '2025-03-22 20:55:49',
                'updated_at' => '2025-03-22 20:55:49',
            ),
            37 => 
            array (
                'id' => 94,
                'user_id' => 228,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Khulna',
                'height_from' => '5\'3"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-22 22:59:17',
                'updated_at' => '2025-03-22 23:15:20',
            ),
            38 => 
            array (
                'id' => 95,
                'user_id' => 231,
                'looking_for' => 'Bride',
                'from_age' => 27,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Khulna',
                'height_from' => '5\'0"',
                'height_to' => '5\'0"',
                'created_at' => '2025-03-23 11:57:27',
                'updated_at' => '2025-03-23 11:57:27',
            ),
            39 => 
            array (
                'id' => 96,
                'user_id' => 232,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => 'Diploma in Engineering',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Rangpur',
                'height_from' => '5\'0"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-23 13:22:46',
                'updated_at' => '2025-03-23 13:22:46',
            ),
            40 => 
            array (
                'id' => 97,
                'user_id' => 233,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 32,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'0"',
                'height_to' => '5\'3"',
                'created_at' => '2025-03-23 17:44:52',
                'updated_at' => '2025-03-23 17:44:52',
            ),
            41 => 
            array (
                'id' => 98,
                'user_id' => 234,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 35,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-23 21:07:17',
                'updated_at' => '2025-03-23 21:07:17',
            ),
            42 => 
            array (
                'id' => 99,
                'user_id' => 235,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Rangpur',
                'height_from' => '5\'4"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-24 01:58:42',
                'updated_at' => '2025-03-24 01:58:42',
            ),
            43 => 
            array (
                'id' => 100,
                'user_id' => 236,
                'looking_for' => 'Groom',
                'from_age' => 21,
                'to_age' => 21,
                'religion' => 'Others',
                'education' => 'Higher Secondary',
                'marital_status' => 'Awaiting Divorce',
                'family_status' => NULL,
                'location' => 'Barishal',
                'height_from' => '5\'1"',
                'height_to' => '5\'1"',
                'created_at' => '2025-03-24 02:03:48',
                'updated_at' => '2025-03-24 02:03:48',
            ),
            44 => 
            array (
                'id' => 101,
                'user_id' => 237,
                'looking_for' => 'Groom',
                'from_age' => 28,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'4"',
                'created_at' => '2025-03-24 02:52:33',
                'updated_at' => '2025-03-24 02:52:33',
            ),
            45 => 
            array (
                'id' => 102,
                'user_id' => 238,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 18,
                'religion' => 'Islam',
                'education' => 'Diploma in Engineering',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Mymensingh',
                'height_from' => '5\'3"',
                'height_to' => '5\'3"',
                'created_at' => '2025-03-24 06:26:55',
                'updated_at' => '2025-03-24 06:26:55',
            ),
            46 => 
            array (
                'id' => 103,
                'user_id' => 239,
                'looking_for' => 'Groom',
                'from_age' => 25,
                'to_age' => 27,
                'religion' => 'Hindu',
                'education' => 'Higher Secondary',
                'marital_status' => 'Widowed',
                'family_status' => NULL,
                'location' => 'Rangpur',
                'height_from' => '5\'7"',
                'height_to' => '5\'5"',
                'created_at' => '2025-03-24 09:46:50',
                'updated_at' => '2025-03-24 09:46:50',
            ),
            47 => 
            array (
                'id' => 104,
                'user_id' => 241,
                'looking_for' => 'Bride',
                'from_age' => 22,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Barishal',
                'height_from' => '5\'4"',
                'height_to' => '5\'9"',
                'created_at' => '2025-03-24 15:29:40',
                'updated_at' => '2025-03-24 15:29:40',
            ),
            48 => 
            array (
                'id' => 105,
                'user_id' => 243,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 28,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'9"',
                'created_at' => '2025-03-24 16:01:12',
                'updated_at' => '2025-03-24 16:01:12',
            ),
            49 => 
            array (
                'id' => 106,
                'user_id' => 244,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => NULL,
                'created_at' => '2025-03-24 17:20:31',
                'updated_at' => '2025-03-24 17:20:31',
            ),
            50 => 
            array (
                'id' => 107,
                'user_id' => 245,
                'looking_for' => 'Groom',
                'from_age' => 25,
                'to_age' => 25,
                'religion' => 'Buddhism',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'6"',
                'created_at' => '2025-03-25 02:25:03',
                'updated_at' => '2025-03-25 02:25:03',
            ),
            51 => 
            array (
                'id' => 108,
                'user_id' => 247,
                'looking_for' => 'Groom',
                'from_age' => NULL,
                'to_age' => 28,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5.4\'',
                'height_to' => '5.10\'',
                'created_at' => '2025-03-25 13:29:37',
                'updated_at' => '2025-03-25 13:29:37',
            ),
            52 => 
            array (
                'id' => 109,
                'user_id' => 248,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 35,
                'religion' => 'No Preference',
                'education' => 'Secondary Education',
                'marital_status' => 'Widowed',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'0"',
                'height_to' => '5\'8"',
                'created_at' => '2025-03-26 01:02:14',
                'updated_at' => '2025-03-26 01:02:14',
            ),
            53 => 
            array (
                'id' => 110,
                'user_id' => 251,
                'looking_for' => 'Bride',
                'from_age' => 35,
                'to_age' => 23,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Widowed',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'1"',
                'created_at' => '2025-03-31 00:20:32',
                'updated_at' => '2025-03-31 00:20:32',
            ),
            54 => 
            array (
                'id' => 111,
                'user_id' => 253,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 40,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '6\'0"',
                'created_at' => '2025-03-31 19:38:32',
                'updated_at' => '2025-03-31 19:38:32',
            ),
            55 => 
            array (
                'id' => 112,
                'user_id' => 254,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 25,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Rajshahi',
                'height_from' => '5\'0"',
                'height_to' => '5\'0"',
                'created_at' => '2025-04-03 00:20:53',
                'updated_at' => '2025-04-03 00:20:53',
            ),
            56 => 
            array (
                'id' => 113,
                'user_id' => 256,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 18,
                'religion' => 'Hindu',
                'education' => 'Fazil',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Barishal',
                'height_from' => '5\'0"',
                'height_to' => '5\'0"',
                'created_at' => '2025-04-03 10:24:37',
                'updated_at' => '2025-04-03 10:24:37',
            ),
            57 => 
            array (
                'id' => 114,
                'user_id' => 257,
                'looking_for' => 'Bride',
                'from_age' => 25,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-04-03 10:54:46',
                'updated_at' => '2025-04-03 10:54:46',
            ),
            58 => 
            array (
                'id' => 115,
                'user_id' => 260,
                'looking_for' => 'Groom',
                'from_age' => 38,
                'to_age' => 38,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Rajshahi',
                'height_from' => '5\'7"',
                'height_to' => '5\'7"',
                'created_at' => '2025-04-03 11:15:16',
                'updated_at' => '2025-04-03 11:15:16',
            ),
            59 => 
            array (
                'id' => 116,
                'user_id' => 262,
                'looking_for' => 'Bride',
                'from_age' => 23,
                'to_age' => 23,
                'religion' => 'Hindu',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Rangpur',
                'height_from' => '5\'2"',
                'height_to' => '5\'0"',
                'created_at' => '2025-04-03 12:27:01',
                'updated_at' => '2025-04-03 12:27:01',
            ),
            60 => 
            array (
                'id' => 117,
                'user_id' => 268,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'1"',
                'height_to' => '5\'4"',
                'created_at' => '2025-04-07 04:20:35',
                'updated_at' => '2025-04-07 04:20:35',
            ),
            61 => 
            array (
                'id' => 118,
                'user_id' => 269,
                'looking_for' => 'Groom',
                'from_age' => 26,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Barishal',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-04-08 01:08:55',
                'updated_at' => '2025-04-08 01:08:55',
            ),
            62 => 
            array (
                'id' => 119,
                'user_id' => 270,
                'looking_for' => 'Bride',
                'from_age' => 21,
                'to_age' => 21,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-04-09 01:57:50',
                'updated_at' => '2025-04-09 01:57:50',
            ),
            63 => 
            array (
                'id' => 120,
                'user_id' => 273,
                'looking_for' => 'Bride',
                'from_age' => 24,
                'to_age' => 28,
                'religion' => 'Islam',
                'education' => 'Fazil',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'4"',
                'height_to' => '5\'4"',
                'created_at' => '2025-04-11 00:06:51',
                'updated_at' => '2025-04-11 00:06:51',
            ),
            64 => 
            array (
                'id' => 121,
                'user_id' => 274,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 26,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'3"',
                'height_to' => '5\'8"',
                'created_at' => '2025-04-12 00:04:19',
                'updated_at' => '2025-04-12 00:04:19',
            ),
            65 => 
            array (
                'id' => 122,
                'user_id' => 277,
                'looking_for' => 'Groom',
                'from_age' => 27,
                'to_age' => 32,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'9"',
                'height_to' => '6\'0"',
                'created_at' => '2025-04-12 23:05:15',
                'updated_at' => '2025-04-12 23:05:15',
            ),
            66 => 
            array (
                'id' => 123,
                'user_id' => 279,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'1"',
                'height_to' => '5\'5"',
                'created_at' => '2025-04-13 14:11:58',
                'updated_at' => '2025-04-13 15:00:43',
            ),
            67 => 
            array (
                'id' => 124,
                'user_id' => 43,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'4"',
                'created_at' => '2025-04-13 16:45:35',
                'updated_at' => '2025-04-13 16:45:35',
            ),
            68 => 
            array (
                'id' => 125,
                'user_id' => 281,
                'looking_for' => 'Bride',
                'from_age' => 45,
                'to_age' => 40,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-04-14 01:12:21',
                'updated_at' => '2025-04-14 01:12:21',
            ),
            69 => 
            array (
                'id' => 126,
                'user_id' => 39,
                'looking_for' => 'Groom',
                'from_age' => 18,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'0"',
                'height_to' => '5\'2"',
                'created_at' => '2025-04-14 02:08:18',
                'updated_at' => '2025-04-14 02:08:18',
            ),
            70 => 
            array (
                'id' => 127,
                'user_id' => 285,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 18,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Khulna',
                'height_from' => '5\'2"',
                'height_to' => '5\'3"',
                'created_at' => '2025-04-14 15:57:36',
                'updated_at' => '2025-04-14 15:57:36',
            ),
            71 => 
            array (
                'id' => 128,
                'user_id' => 287,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 19,
                'religion' => 'Islam',
                'education' => 'Higher Secondary',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'3"',
                'height_to' => '5\'6"',
                'created_at' => '2025-04-18 11:27:51',
                'updated_at' => '2025-04-18 11:27:51',
            ),
            72 => 
            array (
                'id' => 129,
                'user_id' => 288,
                'looking_for' => 'Bride',
                'from_age' => NULL,
                'to_age' => 40,
                'religion' => 'Not Specified',
                'education' => 'Not Applied',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Mymenshingh',
                'height_from' => '5.0\'',
                'height_to' => '6.0\'',
                'created_at' => '2025-04-18 11:41:17',
                'updated_at' => '2025-04-18 11:41:17',
            ),
            73 => 
            array (
                'id' => 130,
                'user_id' => 289,
                'looking_for' => 'Groom',
                'from_age' => 22,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Mymensingh',
                'height_from' => '5\'3"',
                'height_to' => '5\'5"',
                'created_at' => '2025-04-18 12:20:35',
                'updated_at' => '2025-04-18 12:20:35',
            ),
            74 => 
            array (
                'id' => 131,
                'user_id' => 291,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 18,
                'religion' => 'Islam',
                'education' => 'Secondary Education',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'0"',
                'height_to' => '5\'2"',
                'created_at' => '2025-04-28 23:29:48',
                'updated_at' => '2025-04-28 23:29:48',
            ),
            75 => 
            array (
                'id' => 132,
                'user_id' => 292,
                'looking_for' => 'Bride',
                'from_age' => NULL,
                'to_age' => 24,
                'religion' => 'Islam',
                'education' => 'Not Applied',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5.0\'',
                'height_to' => '5.6\'',
                'created_at' => '2025-05-05 22:52:48',
                'updated_at' => '2025-05-05 22:52:48',
            ),
            76 => 
            array (
                'id' => 133,
                'user_id' => 293,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 22,
                'religion' => 'Islam',
                'education' => 'Diploma',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '4\'2"',
                'height_to' => '4\'7"',
                'created_at' => '2025-05-19 16:34:00',
                'updated_at' => '2025-07-01 11:15:31',
            ),
            77 => 
            array (
                'id' => 134,
                'user_id' => 294,
                'looking_for' => 'Bride',
                'from_age' => 18,
                'to_age' => 29,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-06-11 21:56:29',
                'updated_at' => '2025-06-11 21:56:29',
            ),
            78 => 
            array (
                'id' => 135,
                'user_id' => 295,
                'looking_for' => 'Groom',
                'from_age' => 36,
                'to_age' => 45,
                'religion' => 'No Preference',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'10"',
                'height_to' => '6\'0"',
                'created_at' => '2025-06-11 22:01:29',
                'updated_at' => '2025-06-11 22:01:29',
            ),
            79 => 
            array (
                'id' => 136,
                'user_id' => 296,
                'looking_for' => 'Groom',
                'from_age' => 26,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'6"',
                'height_to' => '5\'8"',
                'created_at' => '2025-06-11 22:29:12',
                'updated_at' => '2025-06-11 22:29:12',
            ),
            80 => 
            array (
                'id' => 137,
                'user_id' => 297,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 34,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'5"',
                'height_to' => '5\'10"',
                'created_at' => '2025-06-11 22:43:46',
                'updated_at' => '2025-06-11 22:43:46',
            ),
            81 => 
            array (
                'id' => 138,
                'user_id' => 298,
                'looking_for' => 'Groom',
                'from_age' => 26,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'5"',
                'height_to' => '5\'10"',
                'created_at' => '2025-06-11 22:45:33',
                'updated_at' => '2025-06-11 22:45:33',
            ),
            82 => 
            array (
                'id' => 139,
                'user_id' => 299,
                'looking_for' => 'Bride',
                'from_age' => 23,
                'to_age' => 26,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Mymensingh',
                'height_from' => NULL,
                'height_to' => NULL,
                'created_at' => '2025-06-11 22:58:45',
                'updated_at' => '2025-06-11 22:58:45',
            ),
            83 => 
            array (
                'id' => 140,
                'user_id' => 300,
                'looking_for' => 'Groom',
                'from_age' => 38,
                'to_age' => 40,
                'religion' => 'Islam',
                'education' => 'Diploma in Engineering',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'10"',
                'height_to' => '5\'11"',
                'created_at' => '2025-06-11 23:11:46',
                'updated_at' => '2025-06-11 23:11:46',
            ),
            84 => 
            array (
                'id' => 141,
                'user_id' => 301,
                'looking_for' => 'Groom',
                'from_age' => 29,
                'to_age' => 32,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'8"',
                'created_at' => '2025-06-11 23:27:34',
                'updated_at' => '2025-06-11 23:27:34',
            ),
            85 => 
            array (
                'id' => 142,
                'user_id' => 302,
                'looking_for' => 'Groom',
                'from_age' => 29,
                'to_age' => 32,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'8"',
                'created_at' => '2025-06-12 03:35:55',
                'updated_at' => '2025-06-12 03:35:55',
            ),
            86 => 
            array (
                'id' => 143,
                'user_id' => 303,
                'looking_for' => 'Groom',
                'from_age' => 32,
                'to_age' => 38,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'10"',
                'created_at' => '2025-06-12 04:39:22',
                'updated_at' => '2025-06-12 04:49:18',
            ),
            87 => 
            array (
                'id' => 144,
                'user_id' => 304,
                'looking_for' => 'Groom',
                'from_age' => 35,
                'to_age' => 37,
                'religion' => 'Islam',
                'education' => 'Doctorate',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'10"',
                'created_at' => '2025-06-12 04:42:37',
                'updated_at' => '2025-06-12 04:42:37',
            ),
            88 => 
            array (
                'id' => 145,
                'user_id' => 305,
                'looking_for' => 'Groom',
                'from_age' => 26,
                'to_age' => 28,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'7"',
                'height_to' => '5\'9"',
                'created_at' => '2025-06-12 10:42:46',
                'updated_at' => '2025-06-12 10:42:46',
            ),
            89 => 
            array (
                'id' => 146,
                'user_id' => 306,
                'looking_for' => 'Groom',
                'from_age' => 26,
                'to_age' => 29,
                'religion' => 'Islam',
                'education' => NULL,
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Khulna',
                'height_from' => '5\'10"',
                'height_to' => '5\'11"',
                'created_at' => '2025-06-12 13:48:10',
                'updated_at' => '2025-06-12 13:48:10',
            ),
            90 => 
            array (
                'id' => 147,
                'user_id' => 307,
                'looking_for' => 'Groom',
                'from_age' => 27,
                'to_age' => 33,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => NULL,
                'created_at' => '2025-06-12 20:02:08',
                'updated_at' => '2025-06-12 20:02:08',
            ),
            91 => 
            array (
                'id' => 148,
                'user_id' => 308,
                'looking_for' => 'Groom',
                'from_age' => 25,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'7"',
                'height_to' => '5\'11"',
                'created_at' => '2025-06-13 00:41:13',
                'updated_at' => '2025-06-13 00:41:13',
            ),
            92 => 
            array (
                'id' => 149,
                'user_id' => 309,
                'looking_for' => 'Groom',
                'from_age' => 24,
                'to_age' => 30,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'8"',
                'height_to' => '6\'0"',
                'created_at' => '2025-06-13 18:45:32',
                'updated_at' => '2025-06-13 18:45:32',
            ),
            93 => 
            array (
                'id' => 150,
                'user_id' => 310,
                'looking_for' => 'Bride',
                'from_age' => 20,
                'to_age' => 27,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'2"',
                'height_to' => '5\'5"',
                'created_at' => '2025-06-13 19:14:06',
                'updated_at' => '2025-06-13 19:14:06',
            ),
            94 => 
            array (
                'id' => 151,
                'user_id' => 311,
                'looking_for' => 'Bride',
                'from_age' => NULL,
                'to_age' => 29,
                'religion' => 'Islam',
                'education' => 'Higher Secondary Education',
                'marital_status' => NULL,
                'family_status' => NULL,
                'location' => 'Rangpur',
                'height_from' => '5.7\'',
                'height_to' => '5.11\'',
                'created_at' => '2025-06-14 23:18:30',
                'updated_at' => '2025-06-14 23:18:30',
            ),
            95 => 
            array (
                'id' => 152,
                'user_id' => 312,
                'looking_for' => 'Groom',
                'from_age' => 27,
                'to_age' => 34,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'4"',
                'height_to' => '6\'5"',
                'created_at' => '2025-06-16 03:47:45',
                'updated_at' => '2025-06-16 03:47:45',
            ),
            96 => 
            array (
                'id' => 153,
                'user_id' => 313,
                'looking_for' => 'Groom',
                'from_age' => 30,
                'to_age' => 34,
                'religion' => 'Islam',
                'education' => 'Master\'s',
                'marital_status' => 'Single',
                'family_status' => NULL,
                'location' => 'Chittagong',
                'height_from' => '5\'5"',
                'height_to' => '5\'6"',
                'created_at' => '2025-06-16 21:08:36',
                'updated_at' => '2025-06-16 21:11:13',
            ),
            97 => 
            array (
                'id' => 154,
                'user_id' => 314,
                'looking_for' => 'Groom',
                'from_age' => 35,
                'to_age' => 45,
                'religion' => 'Islam',
                'education' => 'Bachelor\'s',
                'marital_status' => 'Divorced',
                'family_status' => NULL,
                'location' => 'Dhaka',
                'height_from' => '5\'5"',
                'height_to' => '5\'8"',
                'created_at' => '2025-06-17 14:33:20',
                'updated_at' => '2025-06-17 14:33:20',
            ),
        ));
        
        
    }
}